In [1]:
import numpy as np

In [3]:
N = 10
true_probs = np.random.dirichlet([5, 2, 2], size=N)
print(true_probs)

predicted_probs = true_probs + np.random.normal(0, 0.05, true_probs.shape)
predicted_probs = np.clip(predicted_probs, 0, None)
predicted_probs = predicted_probs / predicted_probs.sum(axis=1, keepdims=True)

print(predicted_probs)

[[0.53304414 0.10545726 0.3614986 ]
 [0.41330575 0.14831706 0.4383772 ]
 [0.42241885 0.20413704 0.37344411]
 [0.35679809 0.1999081  0.44329381]
 [0.61832566 0.09742825 0.2842461 ]
 [0.58913545 0.23899775 0.17186681]
 [0.76767046 0.06435439 0.16797515]
 [0.68792021 0.04226238 0.26981741]
 [0.39320969 0.28009671 0.3266936 ]
 [0.59126192 0.21154089 0.19719718]]
[[0.56448937 0.02989592 0.40561471]
 [0.38400007 0.20241203 0.4135879 ]
 [0.43103732 0.20559847 0.36336421]
 [0.37959043 0.19437123 0.42603834]
 [0.62309832 0.1419395  0.23496218]
 [0.6041702  0.2435238  0.15230599]
 [0.8159084  0.00914572 0.17494588]
 [0.66514075 0.09934319 0.23551606]
 [0.40833788 0.21577905 0.37588307]
 [0.59864829 0.26445985 0.13689186]]
